### ISSUE TITLE
H&L likelihood crashes when run on nside=512

### ISSUE THREAD

**Issue by kwolz** [simonsobs/BBPower#6]
When running [`BBCompSep`](https://github.com/simonsobs/BBPower/blob/caa2eff4852892b4d9ec6e0a63a4902db74b149a/bbpower/compsep.py) with the `h&l` likelihood, the code crashes. The maps that I tested this on were taken from BBSims (Gaussian FGs + baseline optimistic noise + CMB with r=0, AL=1). I first ran BBPowerSpecter and BBPowerSummarizer on 100 sims to get the covariance matrix. 
The relevant error message from `BBCompSep` is the following:
```
/global/u2/k/kwolz/BBPower/bbpower/compsep.py:552: RuntimeWarning: invalid value encountered in sqrt
  roots_m = np.sqrt(diag_m) # 512/full/r0/rfree/g/bl/w:
/global/u2/k/kwolz/BBPower/bbpower/compsep.py:567: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(diag) # 512/full/r0/rfree/g/bl/w: first two out of six elements in 'roots' are always nan
Traceback (most recent call last):
  File "/global/homes/k/kwolz/.conda/envs/testenv/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/global/homes/k/kwolz/.conda/envs/testenv/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/global/u2/k/kwolz/BBPower/bbpower/__main__.py", line 5, in <module>
    PipelineStage.main()
  File "/global/u2/k/kwolz/BBPipe/bbpipe/stage.py", line 553, in main
    stage.execute(args)
  File "/global/u2/k/kwolz/BBPipe/bbpipe/stage.py", line 623, in execute
    stage.run()
  File "/global/u2/k/kwolz/BBPower/bbpower/compsep.py", line 762, in run
    sampler = self.polychord_sampler()
  File "/global/u2/k/kwolz/BBPower/bbpower/compsep.py", line 691, in polychord_sampler
    prior, dumper)
  File "/global/homes/k/kwolz/.conda/envs/testenv/lib/python3.6/site-packages/pypolychord/__init__.py", line 224, in run_polychord
    settings.seed)
  File "/global/homes/k/kwolz/.conda/envs/testenv/lib/python3.6/site-packages/pypolychord/__init__.py", line 186, in wrap_loglikelihood
    logL, phi[:] = loglikelihood(theta)
  File "/global/u2/k/kwolz/BBPower/bbpower/compsep.py", line 661, in likelihood
    return self.lnlike(theta), [0]
  File "/global/u2/k/kwolz/BBPower/bbpower/compsep.py", line 601, in lnlike
    dx = self.h_and_l_dx(params)
  File "/global/u2/k/kwolz/BBPower/bbpower/compsep.py", line 554, in h_and_l_dx
    X = self.h_and_l(C, self.observed_cls[k], self.Cfl_sqrt[k])
  File "/global/u2/k/kwolz/BBPower/bbpower/compsep.py", line 580, in h_and_l
    Cfl_sqrt.dot(rot, U) # 512/full/r0/rfree/g/bl/w: this is a complex-valued matrix
ValueError: output array is not acceptable (must have the right datatype, number of dimensions, and be a C-Array)
Executing stage: BBCompSep
Running PolyChord sampler
-inf

PolyChord: Next Generation Nested Sampling
copyright: Will Handley, Mike Hobson & Anthony Lasenby
  version: 1.15.1
  release: 9th Sep 2018
    email: wh260@mrao.cam.ac.uk
```

**Comment by kwolz** [comment]
In case it's useful, this is the relevant `config.yml` file:
```
# These parameters are accessible to all stages
global:
    nside: 512
    compute_dell: True

BBPowerSpecter:
    # Bandpower definition
    bpw_edges: "/global/cscratch1/sd/kwolz/BBPower/examples/data/bpw_edges.txt"
    purify_B: True
    n_iter : 3
    # Activates parallelization with mpi4py
    parallel: True
    
BBPowerSpecterSplits:
    bpw_edges: "/global/cscratch1/sd/kwolz/BBPower/examples/data/bpw_edges.txt"
    purify_B: True
    n_iter : 3

BBPowerSummarizer:
    # Covariance types
    nulls_covar_type: "diagonal"
    nulls_covar_diag_order: 0
    data_covar_type: "block_diagonal"
    data_covar_diag_order: 0

BBCompSep:
    # Sampler type (choose 'emcee', 'polychord', 'maximum_likelihood', 
    # 'single_point' or 'timing')
    #sampler: 'emcee'
    sampler: 'polychord'
    # If you chose polychord:
    nlive: 50
    nrepeat: 50
    # If you chose emcee:
    nwalkers: 24
    n_iters: 5000
    # Likelihood type (choose 'chi2' or 'h&l')
    likelihood_type: 'h&l'
    # What is the starting point?
    r_init: 1.e-3
    # Which polarization channels do you want to include?
    pol_channels: ['B']
    # Scale cuts (will apply to all frequencies)
    l_min: 30
    l_max: 300

    # CMB model
    cmb_model:
        # Template power spectrum. Should contained the lensed power spectra
        # with r=0 and r=1 respectively.
        cmb_templates: ['/global/cscratch1/sd/kwolz/BBPower/examples/data/camb_lens_nobb_nico.dat',
                        '/global/cscratch1/sd/kwolz/BBPower/examples/data/camb_lens_r1_nico.dat']
        # Free parameters
        params:
            # tensor-to-scalar ratio
            # See below for the meaning of the different elements in the list.
            r_tensor: ['r_tensor', 'tophat', [-0.1, 0.00, 0.1]]
            #r_tensor: ['r_tensor', 'fixed', [0.00]]
            # Lensing amplitude
            A_lens: ['A_lens', 'tophat', [0.00, 1.0, 2.00]]
            #A_lens: ['A_lens', 'fixed', [1.00]]

    # Foreground model
    fg_model:
        # Add one section per component. They should be called `component_X`,
        # starting with X=1
        component_1:
            # Name for this component
            name: Dust
            # Type of SED. Should be one of the classes stored in fgbuster.components
            # https://github.com/fgbuster/fgbuster/blob/master/fgbuster/component_model.py
            sed: Dust
            # Type of power spectra for all possible polarization channel combinations.
            # Any combinations not added here will be assumed to be zero.
            # The names should be one of the classes in bbpower/fgcls.py
            cl:
                EE: ClPowerLaw
                BB: ClPowerLaw
            # Parameters of the SED
            sed_parameters:
                # The key can be anything you want, but each parameter in the model
                # must have a different name.
                # The first item in the list is the name of the parameter used by fgbuster
                # The second item is the type of prior. The last item are the numbers
                # necessary to define the prior. They should be:
                #  - Gaussian: [mean,sigma]
                #  - tophat: [lower edge, start value, upper edge]
                #  - fixed: [parameter value]
                # nu0-type parameters can only be fixed.
                #beta_d: ['beta_d', 'fixed', [1.54]]
                beta_d: ['beta_d', 'Gaussian', [1.54, 0.11]]
                temp_d: ['temp', 'fixed', [20.]]
                nu0_d: ['nu0', 'fixed', [353.]]
            cl_parameters:
                # Same for power spectrum parameters
                # (broken down by polarization channel combinations)
                EE:
                   #amp_d_ee: ['amp', 'tophat', [0., 10., "inf"]]
                   amp_d_ee: ['amp', 'tophat', [40., 56., 80.]]
                   alpha_d_ee: ['alpha', 'tophat', [-1., -0.32, 0.]]
                   l0_d_ee: ['ell0', 'fixed', [80.]]
                BB:
                   #amp_d_bb: ['amp', 'fixed', [28.]]
                   amp_d_bb: ['amp', 'tophat', [0., 28., 50.]]
                   #alpha_d_bb: ['alpha', 'fixed', [-0.16]]
                   alpha_d_bb: ['alpha', 'tophat', [-0.5, 0.0, 0.5]]
                   l0_d_bb: ['ell0', 'fixed', [80.]]
            # If this component should be correlated with any other, list them here
            cross:
                # In this case the list should contain:
                # [component name, prior type, prior parameters]
                epsilon_ds: ['component_2', 'tophat', [-1., 0., 1.]]
                #epsilon_ds: ['component_2', 'fixed', [0.]]

        component_2:
            name: Synchrotron
            sed: Synchrotron
            cl:
                EE: ClPowerLaw
                BB: ClPowerLaw
            sed_parameters:
                beta_s: ['beta_pl', 'Gaussian', [-3.0, 0.3]]
                #beta_s: ['beta_pl', 'fixed', [0.0]]
                nu0_s: ['nu0', 'fixed', [23.]]
            cl_parameters:
                EE:
                    #amp_s_ee: ['amp', 'tophat', [0., 4., "inf"]]
                    amp_s_ee: ['amp', 'tophat', [5., 9., 15.]]
                    alpha_s_ee: ['alpha', 'tophat', [-2., -0.7, 0.]]
                    l0_s_ee: ['ell0', 'fixed', [80.]]
                BB:
                    #amp_s_bb: ['amp', 'tophat', [0., 2., "inf"]]
                    amp_s_bb: ['amp', 'tophat', [0., 1.6, 4.]]
                    #amp_s_bb: ['amp', 'fixed', [0.]]
                    alpha_s_bb: ['alpha', 'tophat', [-2., -0.93, 0.]]
                    #alpha_s_bb: ['alpha', 'fixed', [0.]]
                    l0_s_bb: ['ell0', 'fixed', [80.]]
```

**Comment by damonge** [comment]
Do you know if this error is exclusive of polychord? I.e. it doesn't happen with emcee?

**Comment by kwolz** [comment]
I'm almost sure it happened with emcee as well. Besides, the problematic function seems to be `h_and_l` which get called also when using emcee.
